services:
  - type: web
    name: english-nlp-tool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    envVars:
      - key: FLASK_ENV
        value: production